example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pyfb_kamailio.urls', namespace='pyfb-kamailio')),
]

pyfb_kamailio/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

app_name = 'pyfb_kamailio'

router = routers.DefaultRouter()
router.register(r'dialog', api.DialogViewSet)
router.register(r'dialogvar', api.DialogVarViewSet)
router.register(r'acc', api.AccViewSet)
router.register(r'acccdr', api.AccCdrViewSet)
router.register(r'missedcall', api.MissedCallViewSet)
router.register(r'uacreg', api.UacRegViewSet)
router.register(r'trusted', api.TrustedViewSet)
router.register(r'version', api.VersionViewSet)
router.register(r'location', api.LocationViewSet)
router.register(r'locationattrs', api.LocationAttrsViewSet)
router.register(r'userblacklist', api.UserBlackListViewSet)
router.register(r'globalblacklist', api.GlobalBlackListViewSet)
router.register(r'speeddial', api.SpeedDialViewSet)
router.register(r'pipelimit', api.PipeLimitViewSet)
router.register(r'mtree', api.MtreeViewSet)
router.register(r'mtrees', api.MtreesViewSet)
router.register(r'htable', api.HtableViewSet)
router.register(r'rtpengine', api.RtpEngineViewSet)

urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Dialog
    path('pyfb_kamailio/dialog/', views.DialogListView.as_view(), name='pyfb_kamailio_dialog_list'),
    path('pyfb_kamailio/dialog/create/', views.DialogCreateView.as_view(), name='pyfb_kamailio_dialog_create'),
    path('pyfb_kamailio/dialog/detail/<int:pk>/', views.DialogDetailView.as_view(), name='pyfb_kamailio_dialog_detail'),
    path('pyfb_kamailio/dialog/update/<int:pk>/', views.DialogUpdateView.as_view(), name='pyfb_kamailio_dialog_update'),
)

urlpatterns += (
    # urls for DialogVar
    path('pyfb_kamailio/dialogvar/', views.DialogVarListView.as_view(), name='pyfb_kamailio_dialogvar_list'),
    path('pyfb_kamailio/dialogvar/create/', views.DialogVarCreateView.as_view(), name='pyfb_kamailio_dialogvar_create'),
    path('pyfb_kamailio/dialogvar/detail/<int:pk>/', views.DialogVarDetailView.as_view(), name='pyfb_kamailio_dialogvar_detail'),
    path('pyfb_kamailio/dialogvar/update/<int:pk>/', views.DialogVarUpdateView.as_view(), name='pyfb_kamailio_dialogvar_update'),
)

urlpatterns += (
    # urls for Acc
    path('pyfb_kamailio/acc/', views.AccListView.as_view(), name='pyfb_kamailio_acc_list'),
    path('pyfb_kamailio/acc/create/', views.AccCreateView.as_view(), name='pyfb_kamailio_acc_create'),
    path('pyfb_kamailio/acc/detail/<int:pk>/', views.AccDetailView.as_view(), name='pyfb_kamailio_acc_detail'),
    path('pyfb_kamailio/acc/update/<int:pk>/', views.AccUpdateView.as_view(), name='pyfb_kamailio_acc_update'),
)

urlpatterns += (
    # urls for AccCdr
    path('pyfb_kamailio/acccdr/', views.AccCdrListView.as_view(), name='pyfb_kamailio_acccdr_list'),
    path('pyfb_kamailio/acccdr/create/', views.AccCdrCreateView.as_view(), name='pyfb_kamailio_acccdr_create'),
    path('pyfb_kamailio/acccdr/detail/<int:pk>/', views.AccCdrDetailView.as_view(), name='pyfb_kamailio_acccdr_detail'),
    path('pyfb_kamailio/acccdr/update/<int:pk>/', views.AccCdrUpdateView.as_view(), name='pyfb_kamailio_acccdr_update'),
)

urlpatterns += (
    # urls for MissedCall
    path('pyfb_kamailio/missedcall/', views.MissedCallListView.as_view(), name='pyfb_kamailio_missedcall_list'),
    path('pyfb_kamailio/missedcall/create/', views.MissedCallCreateView.as_view(), name='pyfb_kamailio_missedcall_create'),
    path('pyfb_kamailio/missedcall/detail/<int:pk>/', views.MissedCallDetailView.as_view(), name='pyfb_kamailio_missedcall_detail'),
    path('pyfb_kamailio/missedcall/update/<int:pk>/', views.MissedCallUpdateView.as_view(), name='pyfb_kamailio_missedcall_update'),
)

urlpatterns += (
    # urls for UacReg
    path('pyfb_kamailio/uacreg/', views.UacRegListView.as_view(), name='pyfb_kamailio_uacreg_list'),
    path('pyfb_kamailio/uacreg/create/', views.UacRegCreateView.as_view(), name='pyfb_kamailio_uacreg_create'),
    path('pyfb_kamailio/uacreg/detail/<int:pk>/', views.UacRegDetailView.as_view(), name='pyfb_kamailio_uacreg_detail'),
    path('pyfb_kamailio/uacreg/update/<int:pk>/', views.UacRegUpdateView.as_view(), name='pyfb_kamailio_uacreg_update'),
)

urlpatterns += (
    # urls for Trusted
    path('pyfb_kamailio/trusted/', views.TrustedListView.as_view(), name='pyfb_kamailio_trusted_list'),
    path('pyfb_kamailio/trusted/create/', views.TrustedCreateView.as_view(), name='pyfb_kamailio_trusted_create'),
    path('pyfb_kamailio/trusted/detail/<int:pk>/', views.TrustedDetailView.as_view(), name='pyfb_kamailio_trusted_detail'),
    path('pyfb_kamailio/trusted/update/<int:pk>/', views.TrustedUpdateView.as_view(), name='pyfb_kamailio_trusted_update'),
)

urlpatterns += (
    # urls for Version
    path('pyfb_kamailio/version/', views.VersionListView.as_view(), name='pyfb_kamailio_version_list'),
    path('pyfb_kamailio/version/create/', views.VersionCreateView.as_view(), name='pyfb_kamailio_version_create'),
    path('pyfb_kamailio/version/detail/<int:pk>/', views.VersionDetailView.as_view(), name='pyfb_kamailio_version_detail'),
    path('pyfb_kamailio/version/update/<int:pk>/', views.VersionUpdateView.as_view(), name='pyfb_kamailio_version_update'),
)

urlpatterns += (
    # urls for Location
    path('pyfb_kamailio/location/', views.LocationListView.as_view(), name='pyfb_kamailio_location_list'),
    path('pyfb_kamailio/location/create/', views.LocationCreateView.as_view(), name='pyfb_kamailio_location_create'),
    path('pyfb_kamailio/location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='pyfb_kamailio_location_detail'),
    path('pyfb_kamailio/location/update/<int:pk>/', views.LocationUpdateView.as_view(), name='pyfb_kamailio_location_update'),
)

urlpatterns += (
    # urls for LocationAttrs
    path('pyfb_kamailio/locationattrs/', views.LocationAttrsListView.as_view(), name='pyfb_kamailio_locationattrs_list'),
    path('pyfb_kamailio/locationattrs/create/', views.LocationAttrsCreateView.as_view(), name='pyfb_kamailio_locationattrs_create'),
    path('pyfb_kamailio/locationattrs/detail/<int:pk>/', views.LocationAttrsDetailView.as_view(), name='pyfb_kamailio_locationattrs_detail'),
    path('pyfb_kamailio/locationattrs/update/<int:pk>/', views.LocationAttrsUpdateView.as_view(), name='pyfb_kamailio_locationattrs_update'),
)

urlpatterns += (
    # urls for UserBlackList
    path('pyfb_kamailio/userblacklist/', views.UserBlackListListView.as_view(), name='pyfb_kamailio_userblacklist_list'),
    path('pyfb_kamailio/userblacklist/create/', views.UserBlackListCreateView.as_view(), name='pyfb_kamailio_userblacklist_create'),
    path('pyfb_kamailio/userblacklist/detail/<int:pk>/', views.UserBlackListDetailView.as_view(), name='pyfb_kamailio_userblacklist_detail'),
    path('pyfb_kamailio/userblacklist/update/<int:pk>/', views.UserBlackListUpdateView.as_view(), name='pyfb_kamailio_userblacklist_update'),
)

urlpatterns += (
    # urls for GlobalBlackList
    path('pyfb_kamailio/globalblacklist/', views.GlobalBlackListListView.as_view(), name='pyfb_kamailio_globalblacklist_list'),
    path('pyfb_kamailio/globalblacklist/create/', views.GlobalBlackListCreateView.as_view(), name='pyfb_kamailio_globalblacklist_create'),
    path('pyfb_kamailio/globalblacklist/detail/<int:pk>/', views.GlobalBlackListDetailView.as_view(), name='pyfb_kamailio_globalblacklist_detail'),
    path('pyfb_kamailio/globalblacklist/update/<int:pk>/', views.GlobalBlackListUpdateView.as_view(), name='pyfb_kamailio_globalblacklist_update'),
)

urlpatterns += (
    # urls for SpeedDial
    path('pyfb_kamailio/speeddial/', views.SpeedDialListView.as_view(), name='pyfb_kamailio_speeddial_list'),
    path('pyfb_kamailio/speeddial/create/', views.SpeedDialCreateView.as_view(), name='pyfb_kamailio_speeddial_create'),
    path('pyfb_kamailio/speeddial/detail/<int:pk>/', views.SpeedDialDetailView.as_view(), name='pyfb_kamailio_speeddial_detail'),
    path('pyfb_kamailio/speeddial/update/<int:pk>/', views.SpeedDialUpdateView.as_view(), name='pyfb_kamailio_speeddial_update'),
)

urlpatterns += (
    # urls for PipeLimit
    path('pyfb_kamailio/pipelimit/', views.PipeLimitListView.as_view(), name='pyfb_kamailio_pipelimit_list'),
    path('pyfb_kamailio/pipelimit/create/', views.PipeLimitCreateView.as_view(), name='pyfb_kamailio_pipelimit_create'),
    path('pyfb_kamailio/pipelimit/detail/<int:pk>/', views.PipeLimitDetailView.as_view(), name='pyfb_kamailio_pipelimit_detail'),
    path('pyfb_kamailio/pipelimit/update/<int:pk>/', views.PipeLimitUpdateView.as_view(), name='pyfb_kamailio_pipelimit_update'),
)

urlpatterns += (
    # urls for Mtree
    path('pyfb_kamailio/mtree/', views.MtreeListView.as_view(), name='pyfb_kamailio_mtree_list'),
    path('pyfb_kamailio/mtree/create/', views.MtreeCreateView.as_view(), name='pyfb_kamailio_mtree_create'),
    path('pyfb_kamailio/mtree/detail/<int:pk>/', views.MtreeDetailView.as_view(), name='pyfb_kamailio_mtree_detail'),
    path('pyfb_kamailio/mtree/update/<int:pk>/', views.MtreeUpdateView.as_view(), name='pyfb_kamailio_mtree_update'),
)

urlpatterns += (
    # urls for Mtrees
    path('pyfb_kamailio/mtrees/', views.MtreesListView.as_view(), name='pyfb_kamailio_mtrees_list'),
    path('pyfb_kamailio/mtrees/create/', views.MtreesCreateView.as_view(), name='pyfb_kamailio_mtrees_create'),
    path('pyfb_kamailio/mtrees/detail/<int:pk>/', views.MtreesDetailView.as_view(), name='pyfb_kamailio_mtrees_detail'),
    path('pyfb_kamailio/mtrees/update/<int:pk>/', views.MtreesUpdateView.as_view(), name='pyfb_kamailio_mtrees_update'),
)

urlpatterns += (
    # urls for Htable
    path('pyfb_kamailio/htable/', views.HtableListView.as_view(), name='pyfb_kamailio_htable_list'),
    path('pyfb_kamailio/htable/create/', views.HtableCreateView.as_view(), name='pyfb_kamailio_htable_create'),

pyfb_kamailio/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Dialog, DialogVar, Acc, AccCdr, MissedCall, UacReg, Trusted, Version, Location, LocationAttrs, UserBlackList, GlobalBlackList, SpeedDial, PipeLimit, Mtree, Mtrees, Htable, RtpEngine, Statistic
from .forms import DialogForm, DialogVarForm, AccForm, AccCdrForm, MissedCallForm, UacRegForm, TrustedForm, VersionForm, LocationForm, LocationAttrsForm, UserBlackListForm, GlobalBlackListForm, SpeedDialForm, PipeLimitForm, MtreeForm, MtreesForm, HtableForm, RtpEngineForm, StatisticForm


class DialogListView(ListView):
    model = Dialog


class DialogCreateView(CreateView):
    model = Dialog
    form_class = DialogForm


class DialogDetailView(DetailView):
    model = Dialog


class DialogUpdateView(UpdateView):
    model = Dialog
    form_class = DialogForm


class DialogVarListView(ListView):
    model = DialogVar


class DialogVarCreateView(CreateView):
    model = DialogVar
    form_class = DialogVarForm


class DialogVarDetailView(DetailView):
    model = DialogVar


class DialogVarUpdateView(UpdateView):
    model = DialogVar
    form_class = DialogVarForm


class AccListView(ListView):
    model = Acc


class AccCreateView(CreateView):
    model = Acc
    form_class = AccForm


class AccDetailView(DetailView):
    model = Acc


class AccUpdateView(UpdateView):
    model = Acc
    form_class = AccForm


class AccCdrListView(ListView):
    model = AccCdr


class AccCdrCreateView(CreateView):
    model = AccCdr
    form_class = AccCdrForm


class AccCdrDetailView(DetailView):
    model = AccCdr


class AccCdrUpdateView(UpdateView):
    model = AccCdr
    form_class = AccCdrForm


class MissedCallListView(ListView):
    model = MissedCall


class MissedCallCreateView(CreateView):
    model = MissedCall
    form_class = MissedCallForm


class MissedCallDetailView(DetailView):
    model = MissedCall


class MissedCallUpdateView(UpdateView):
    model = MissedCall
    form_class = MissedCallForm


class UacRegListView(ListView):
    model = UacReg


class UacRegCreateView(CreateView):
    model = UacReg
    form_class = UacRegForm


class UacRegDetailView(DetailView):
    model = UacReg


class UacRegUpdateView(UpdateView):
    model = UacReg
    form_class = UacRegForm


class TrustedListView(ListView):
    model = Trusted


class TrustedCreateView(CreateView):
    model = Trusted
    form_class = TrustedForm


class TrustedDetailView(DetailView):
    model = Trusted


class TrustedUpdateView(UpdateView):
    model = Trusted
    form_class = TrustedForm


class VersionListView(ListView):
    model = Version


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm


class VersionDetailView(DetailView):
    model = Version


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm


class LocationListView(ListView):
    model = Location


class LocationCreateView(CreateView):
    model = Location
    form_class = LocationForm


class LocationDetailView(DetailView):
    model = Location


class LocationUpdateView(UpdateView):
    model = Location
    form_class = LocationForm


class LocationAttrsListView(ListView):
    model = LocationAttrs


class LocationAttrsCreateView(CreateView):
    model = LocationAttrs
    form_class = LocationAttrsForm


class LocationAttrsDetailView(DetailView):
    model = LocationAttrs


class LocationAttrsUpdateView(UpdateView):
    model = LocationAttrs
    form_class = LocationAttrsForm


class UserBlackListListView(ListView):
    model = UserBlackList


class UserBlackListCreateView(CreateView):
    model = UserBlackList
    form_class = UserBlackListForm


class UserBlackListDetailView(DetailView):
    model = UserBlackList


class UserBlackListUpdateView(UpdateView):
    model = UserBlackList
    form_class = UserBlackListForm


class GlobalBlackListListView(ListView):
    model = GlobalBlackList


class GlobalBlackListCreateView(CreateView):
    model = GlobalBlackList
    form_class = GlobalBlackListForm


class GlobalBlackListDetailView(DetailView):
    model = GlobalBlackList


class GlobalBlackListUpdateView(UpdateView):
    model = GlobalBlackList
    form_class = GlobalBlackListForm


class SpeedDialListView(ListView):
    model = SpeedDial


class SpeedDialCreateView(CreateView):
    model = SpeedDial
    form_class = SpeedDialForm


class SpeedDialDetailView(DetailView):
    model = SpeedDial


class SpeedDialUpdateView(UpdateView):
    model = SpeedDial
    form_class = SpeedDialForm


class PipeLimitListView(ListView):
    model = PipeLimit


class PipeLimitCreateView(CreateView):
    model = PipeLimit
    form_class = PipeLimitForm


class PipeLimitDetailView(DetailView):
    model = PipeLimit


class PipeLimitUpdateView(UpdateView):
    model = PipeLimit
    form_class = PipeLimitForm


class MtreeListView(ListView):
    model = Mtree


class MtreeCreateView(CreateView):
    model = Mtree
    form_class = MtreeForm


class MtreeDetailView(DetailView):
    model = Mtree


class MtreeUpdateView(UpdateView):
    model = Mtree
    form_class = MtreeForm


class MtreesListView(ListView):
    model = Mtrees


class MtreesCreateView(CreateView):
    model = Mtrees
    form_class = MtreesForm


class MtreesDetailView(DetailView):
    model = Mtrees


class MtreesUpdateView(UpdateView):
    model = Mtrees
    form_class = MtreesForm


class HtableListView(ListView):
    model = Htable


class HtableCreateView(CreateView):
    model = Htable
    form_class = HtableForm


class HtableDetailView(DetailView):
    model = Htable


class HtableUpdateView(UpdateView):
    model = Htable
    form_class = HtableForm


class RtpEngineListView(ListView):
    model = RtpEngine


class RtpEngineCreateView(CreateView):
    model = RtpEngine
    form_class = RtpEngineForm


class RtpEngineDetailView(DetailView):
    model = RtpEngine


class RtpEngineUpdateView(UpdateView):
    model = RtpEngine
    form_class = RtpEngineForm


class StatisticListView(ListView):
    model = Statistic


class StatisticCreateView(CreateView):
    model = Statistic
    form_class = StatisticForm


class StatisticDetailView(DetailView):
    model = Statistic


class StatisticUpdateView(UpdateView):
    model = Statistic
    form_class = StatisticForm

pyfb_kamailio/templates/pyfb_kamailio/acc_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_acc_list' %}">Acc Listing</a></p>
<table class="table">
<tr><td>method</td><td>{{ object.method }}</td></tr>
<tr><td>from_tag</td><td>{{ object.from_tag }}</td></tr>
<tr><td>to_tag</td><td>{{ object.to_tag }}</td></tr>
<tr><td>callid</td><td>{{ object.callid }}</td></tr>
<tr><td>sip_code</td><td>{{ object.sip_code }}</td></tr>
<tr><td>sip_reason</td><td>{{ object.sip_reason }}</td></tr>
<tr><td>time</td><td>{{ object.time }}</td></tr>
<tr><td>time_attr</td><td>{{ object.time_attr }}</td></tr>
<tr><td>time_exten</td><td>{{ object.time_exten }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Acc</a>

{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/acc_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_acc_list' %}">Acc Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/acc_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_acc_list' %}">Acc Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>method</td>
    <td>from_tag</td>
    <td>to_tag</td>
    <td>callid</td>
    <td>sip_code</td>
    <td>sip_reason</td>
    <td>time</td>
    <td>time_attr</td>
    <td>time_exten</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.method }}</td>
    <td>{{ object.from_tag }}</td>
    <td>{{ object.to_tag }}</td>
    <td>{{ object.callid }}</td>
    <td>{{ object.sip_code }}</td>
    <td>{{ object.sip_reason }}</td>
    <td>{{ object.time }}</td>
    <td>{{ object.time_attr }}</td>
    <td>{{ object.time_exten }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-kamailio:pyfb_kamailio_acc_create' %}">Create new Acc</a>
{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/acccdr_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_acccdr_list' %}">AccCdr Listing</a></p>
<table class="table">
<tr><td>start_time</td><td>{{ object.start_time }}</td></tr>
<tr><td>end_time</td><td>{{ object.end_time }}</td></tr>
<tr><td>duration</td><td>{{ object.duration }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit AccCdr</a>

{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/dialog_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_dialog_list' %}">Dialog Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>hash_entry</td>
    <td>hash_id</td>
    <td>callid</td>
    <td>from_uri</td>
    <td>from_tag</td>
    <td>to_uri</td>
    <td>to_tag</td>
    <td>caller_cseq</td>
    <td>callee_cseq</td>
    <td>caller_route_set</td>
    <td>callee_route_set</td>
    <td>caller_contact</td>
    <td>callee_contact</td>
    <td>caller_sock</td>
    <td>callee_stock</td>
    <td>state</td>
    <td>start_time</td>
    <td>timeout</td>
    <td>sflags</td>
    <td>iflags</td>
    <td>toroute_name</td>
    <td>req_uri</td>
    <td>xdata</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.hash_entry }}</td>
    <td>{{ object.hash_id }}</td>
    <td>{{ object.callid }}</td>
    <td>{{ object.from_uri }}</td>
    <td>{{ object.from_tag }}</td>
    <td>{{ object.to_uri }}</td>
    <td>{{ object.to_tag }}</td>
    <td>{{ object.caller_cseq }}</td>
    <td>{{ object.callee_cseq }}</td>
    <td>{{ object.caller_route_set }}</td>
    <td>{{ object.callee_route_set }}</td>
    <td>{{ object.caller_contact }}</td>
    <td>{{ object.callee_contact }}</td>
    <td>{{ object.caller_sock }}</td>
    <td>{{ object.callee_stock }}</td>
    <td>{{ object.state }}</td>
    <td>{{ object.start_time }}</td>
    <td>{{ object.timeout }}</td>
    <td>{{ object.sflags }}</td>
    <td>{{ object.iflags }}</td>
    <td>{{ object.toroute_name }}</td>
    <td>{{ object.req_uri }}</td>
    <td>{{ object.xdata }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-kamailio:pyfb_kamailio_dialog_create' %}">Create new Dialog</a>
{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/globalblacklist_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_globalblacklist_list' %}">GlobalBlackList Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>prefix</td>
    <td>whitelist</td>
    <td>description</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.prefix }}</td>
    <td>{{ object.whitelist }}</td>
    <td>{{ object.description }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-kamailio:pyfb_kamailio_globalblacklist_create' %}">Create new GlobalBlackList</a>
{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/htable_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_htable_list' %}">Htable Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>key_name</td>
    <td>key_type</td>
    <td>value_type</td>
    <td>key_value</td>
    <td>expires</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.key_name }}</td>
    <td>{{ object.key_type }}</td>
    <td>{{ object.value_type }}</td>
    <td>{{ object.key_value }}</td>
    <td>{{ object.expires }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-kamailio:pyfb_kamailio_htable_create' %}">Create new Htable</a>
{% endblock %}

pyfb_kamailio/templates/pyfb_kamailio/version_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'pyfb-kamailio:pyfb_kamailio_version_list' %}">Version Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>table_name</td>
    <td>table_version</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.table_name }}</td>
    <td>{{ object.table_version }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'pyfb-kamailio:pyfb_kamailio_version_create' %}">Create new Version</a>
{% endblock %}